trigger: none

schedules:
- cron: "5 8,9 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: euserv

jobs:

- job: build
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client euserv --username $USERNAME --password $PASSWORD
    displayName: 'Run'