trigger: none

schedules:
- cron: "0 0-4,6 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

jobs:

- job: build
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - bash: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    env:
      AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
    displayName: 'Login Azure DevOps Extension'

  - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
    displayName: 'Set default Azure DevOps organization and project'

  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      script: |
        import json
        import os
        import time

        data = os.popen('az pipelines list').read()
        data = json.loads(data)
        for i in data:
            os.system(f"az pipelines run --id {i['id']}")
            time.sleep(1)
