trigger: none

schedules:
- cron: "0 0-4,6 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

jobs:

- job: build
  timeoutInMinutes: 20

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - bash: echo $(AZURE_DEVOPS_CLI_PAT) | az devops login
    env:
      AZURE_DEVOPS_CLI_PAT: $(AZURE_DEVOPS_TOKEN)
    displayName: 'Login Azure DevOps Extension'

  - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
    displayName: 'Set default Azure DevOps organization and project'

  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      script: |
        import os
        import json
        from concurrent.futures.thread import ThreadPoolExecutor

        def run_pip(_id, _name):
            if _name != 'run':
                os.system(f"az pipelines run --id {_id} > /dev/null")

        try:
            data = os.popen('az pipelines list').read()
            if data:
                data = json.loads(data)

                with ThreadPoolExecutor(max_workers=5) as executor:
                    args = ((i['id'], i['name']) for i in data)
                    executor.map(lambda a: run_pip(*a), args, chunksize=2)
        except Exception as e:
            print(e)
