name: main

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - '.github/workflows/main.yml'

jobs:
  Run:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install requirements
      run: pip3 install -r requirements.txt

    - name: Run
      run: python3 main.py --client linux --username ${{ secrets.USERNAME_LINUX_DO }} --password ${{ secrets.PASSWORD_LINUX_DO }}
